version: '3'
services:
  tf:
    build: .
    image: contino/terraform
    volumes:
      - type: bind
        source: .
        target: /opt/app
    working_dir: /opt/app
    env_file: .env
  app:
    build: ./application/
    image: weather-app:1