name: Push Image
on:
  push:
    branches:
      - main
    paths:
      - 'application/**'
  workflow_run:
    workflows: [Deploy]
    branches:
      - main
    types:
      - completed
    paths:
      - 'modules/ecr/**'
      - 'docker-compose.yml'
jobs:
  push_image:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Push_Image
      run: make push_image

  deploy_image:
    environment:
      name: approval
    needs: push_image
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Deploy_image
      run: make deploy_image