name: push
on:
  push:
    branches:
      - main
    paths:
      - 'application/**'
      - 'modules/ecr/**'
      - 'docker-compose.yml'
jobs:
  ecr_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with: 
        filters: |
          tf:
            - 'modules/ecr/**'
            - 'docker-compose.yml'
    - name: Wait for TF Deployment
      if: steps.filter.outputs.tf == 'true'
      uses: fountainhead/action-wait-for-check@v1.0.0
      with:
          token: ${{ secrets.ACCESS_TOKEN }}
          checkName: terraform_apply
          timeoutSeconds: 1800

  push_image:
    needs: ecr_check
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Push_Image
      run: make push_image

  deploy_image:
    environment:
      name: approval
    needs: push_image
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Deploy_image
      run: make deploy_image